var activeTrainingDay=1;
const TRAINING_TEMPLATE=[
{day:1,name:'Wyciskanie na lawce plaskiej',range:'3x5-8',sets:[['90','5'],['90','6'],['90','5'],['','']],note:''},{day:1,name:'Podciaganie (Podchwyt)',range:'3x max',sets:[['','6'],['','7'],['','6'],['','']],note:'ladne pelne'},{day:1,name:'Wyciskanie hantli na skosie dodatnim',range:'3x8-10',sets:[['32,5','10'],['32,5','10'],['32,5','10'],['','']],note:''},{day:1,name:'Wioslowanie sztanga w opadzie',range:'3x8-10',sets:[['55','10'],['55','10'],['55','10'],['','']],note:''},{day:1,name:'Ab wheel',range:'3x12-15',sets:[['','15'],['','15'],['','15'],['','']],note:''},{day:1,name:'Deska bokiem',range:'3x12-15',sets:[['','2x15'],['','2x15'],['','2x15'],['','']],note:''},{day:1,name:'Dotykanie lydek',range:'50',sets:[['','50'],['','50'],['','50'],['','']],note:''},
{day:2,name:'Przysiad',range:'3x4-6',sets:[['90','8'],['90','6'],['90','6'],['','']],note:''},{day:2,name:'OHP stojac',range:'3x6-8',sets:[['55','6'],['55','6'],['',''],['','']],note:''},{day:2,name:'Wypychanie na suwnicy',range:'3x12',sets:[['',''],['',''],['',''],['','']],note:''},{day:2,name:'Unoszenie hantli bokiem',range:'4x10-12',sets:[['9','15'],['9','15'],['9','12'],['9','12']],note:''},{day:2,name:'T-bar row',range:'3x8-10',sets:[['50','10'],['50','10'],['45','10'],['','']],note:''},
{day:3,name:'Martwy ciag',range:'3x4-6',sets:[['140','6'],['140','6'],['140','6'],['','']],note:''},{day:3,name:'Hip thrust',range:'3x10-12',sets:[['',''],['',''],['',''],['','']],note:''},{day:3,name:'Wioslowanie hantlami na lawce',range:'3x10-12',sets:[['12','10'],['16','12'],['16','12'],['','']],note:''},{day:3,name:'Podciaganie negatywne',range:'3x max',sets:[['','6'],['','7'],['','6'],['','']],note:''},{day:3,name:'Reverse fly siedzac',range:'3x10-12',sets:[['6','12 zle'],['4','12'],['4','12'],['','']],note:''},{day:3,name:'TRX/wioslarz',range:'3x20-25',sets:[['3','15'],['3','20'],['3','20'],['','']],note:''},{day:3,name:'Dookola swiata',range:'3x15-20',sets:[['14','2x15'],['14','2x15'],['14','2x15'],['','']],note:''},{day:3,name:'Russian twist',range:'3x15-20x2',sets:[['8','2x15'],['8','2x15'],['8','2x15'],['','']],note:''},
{day:4,name:'Wyciskanie hantli na lawce plaskiej',range:'3x10-12',sets:[['35','10'],['35','10'],['35','10'],['','']],note:''},{day:4,name:'Wyciskanie hantli siedzac (Barki)',range:'3x10-12',sets:[['20','12'],['20','12'],['20','12'],['','']],note:''},{day:4,name:'Rozpietki na skosie dodatnim',range:'3x10-12',sets:[['10','12'],['15','12'],['15','12'],['','']],note:''},{day:4,name:'Unoszenie hantli bokiem',range:'4x10-12',sets:[['9','12'],['9','12'],['9','12'],['','']],note:''},{day:4,name:'Dipy (Triceps/Klatka dol)',range:'3x max',sets:[['','12'],['','12'],['',''],['','']],note:''},
{day:5,name:'Lydki',range:'3x10-12',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'RDL',range:'3x10-12',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'Podciaganie negatywne',range:'3x max',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'Wykroki chodzone z hantlami',range:'3x10x2',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'Wioslowanie hantlami w oparciu',range:'3x10x2',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'Uginanie ramion ze sztanga',range:'3x10x2',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'Allahy',range:'3x12-15',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'Unoszenie nog prostych *na brzuch',range:'3x12-15',sets:[['',''],['',''],['',''],['','']],note:''},{day:5,name:'Przekladanie nog nad czyms',range:'3x15-20',sets:[['',''],['',''],['',''],['','']],note:''}
];
function makeExerciseId(day,index,name){return 'd'+day+'-'+index+'-'+plain(name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function ensureTrainingState(){if(!S.trainingPlanV1){S.trainingPlanV1=TRAINING_TEMPLATE.map(function(item,index){return{id:makeExerciseId(item.day,index,item.name),day:item.day,name:item.name,range:item.range,note:item.note||'',sets:item.sets.map(function(set){return{kg:set[0],reps:set[1]};})};});}if(!S.trainingHistory)S.trainingHistory=[];if(!S.bodyMeasurements)S.bodyMeasurements=[];}
function switchTrainingPage(page,btn){document.querySelectorAll('.training-page').forEach(function(el){el.classList.remove('active');});document.querySelectorAll('.training-tab').forEach(function(el){el.classList.remove('active');});const target=document.getElementById('training-page-'+page);if(target)target.classList.add('active');if(btn)btn.classList.add('active');if(page==='progress')renderTrainingProgress();if(page==='measurements')renderMeasurements();}
function switchTrainingDay(day,btn){activeTrainingDay=day;document.querySelectorAll('.training-day-tab').forEach(function(el){el.classList.remove('active');});if(btn)btn.classList.add('active');renderTrainingPlan();}
function renderTrainingDashboard(){ensureTrainingState();renderTrainingDayTabs();renderTrainingPlan();renderTrainingProgress();renderMeasurements();}
function renderTrainingDayTabs(){const el=document.getElementById('training-day-tabs');if(!el)return;el.innerHTML=[1,2,3,4,5].map(function(day){return '<button class="training-day-tab'+(day===activeTrainingDay?' active':'')+'" onclick="switchTrainingDay('+day+',this)">Day '+day+'</button>';}).join('');}
function renderTrainingPlan(){const list=document.getElementById('training-plan-list');if(!list)return;ensureTrainingState();const exercises=S.trainingPlanV1.filter(function(ex){return ex.day===activeTrainingDay;});list.innerHTML=exercises.map(renderExerciseCard).join('');}
function renderExerciseCard(ex){const sets=[0,1,2,3].map(function(i){const set=ex.sets[i]||{kg:'',reps:''};return `<div class="set-box"><div class="set-head"><span class="set-label">Seria ${i+1}</span><button class="copy-set" ${i===3?'disabled':''} onclick="copyTrainingSet('${ex.id}',${i})">-></button></div><div class="set-inputs"><label>kg<input value="${esc(set.kg)}" inputmode="decimal" onchange="updateTrainingSet('${ex.id}',${i},'kg',this.value)"></label><label>powt.<input value="${esc(set.reps)}" inputmode="decimal" onchange="updateTrainingSet('${ex.id}',${i},'reps',this.value)"></label></div></div>`;}).join('');return `<div class="training-exercise"><div class="training-exercise-top"><div class="training-exercise-name">${esc(ex.name)}</div><div class="training-range">${esc(ex.range)}</div></div><div class="set-grid">${sets}</div><textarea class="training-note" placeholder="Uwagi..." onchange="updateTrainingNote('${ex.id}',this.value)">${esc(ex.note||'')}</textarea></div>`;}
function findTrainingExercise(id){ensureTrainingState();return S.trainingPlanV1.find(function(ex){return ex.id===id;});}
function updateTrainingSet(id,index,field,value){const ex=findTrainingExercise(id);if(!ex)return;if(!ex.sets[index])ex.sets[index]={kg:'',reps:''};ex.sets[index][field]=value.trim();save();}
function copyTrainingSet(id,index){const ex=findTrainingExercise(id);if(!ex||index>=3)return;if(!ex.sets[index])ex.sets[index]={kg:'',reps:''};ex.sets[index+1]={kg:ex.sets[index].kg||'',reps:ex.sets[index].reps||''};save();renderTrainingPlan();}
function updateTrainingNote(id,value){const ex=findTrainingExercise(id);if(!ex)return;ex.note=value.trim();save();}
function toNumber(value){const match=String(value||'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return match?parseFloat(match[0]):0;}
function setScore(set){const kg=toNumber(set.kg);const reps=toNumber(set.reps);if(kg>0&&reps>0)return kg*(1+(reps/30));return reps;}
function bestExerciseScore(ex){let best=0;let bestSet={kg:'',reps:''};(ex.sets||[]).forEach(function(set){const score=setScore(set);if(score>best){best=score;bestSet=set;}});return{score:Math.round(best*10)/10,bestSet:bestSet};}
function saveTrainingSnapshot(){ensureTrainingState();const exercises=S.trainingPlanV1.filter(function(ex){return ex.day===activeTrainingDay;}).map(function(ex){const best=bestExerciseScore(ex);return{id:ex.id,name:ex.name,sets:ex.sets,score:best.score,bestSet:best.bestSet,note:ex.note||''};});S.trainingHistory.unshift({date:tdk(),day:activeTrainingDay,exercises:exercises,createdAt:new Date().toISOString()});S.trainingHistory=S.trainingHistory.slice(0,120);save();renderTrainingProgress();switchTrainingPage('progress',document.querySelector('.training-tab:nth-child(2)'));}
function formatSet(set){if(!set)return '-';if(set.kg&&set.reps)return set.kg+' kg x '+set.reps;if(set.reps)return set.reps+' powt.';if(set.kg)return set.kg+' kg';return '-';}
function renderTrainingProgress(){const el=document.getElementById('training-progress-list');if(!el)return;ensureTrainingState();const history=(S.trainingHistory||[]).slice().reverse();if(history.length===0){el.innerHTML='<div class="progress-card"><div class="progress-empty">Zapisz pierwszy trening dnia, a tutaj pojawia sie progres od startu i z treningu na trening. Licze go na bazie szacowanego 1RM: ciezar x (1 + powtorzenia / 30). Dla cwiczen bez ciezaru licze progres po liczbie powtorzen.</div></div>';return;}const map={};history.forEach(function(session){(session.exercises||[]).forEach(function(ex){if(!map[ex.id])map[ex.id]=[];if(ex.score>0)map[ex.id].push({date:session.date,score:ex.score,set:ex.bestSet,name:ex.name});});});const cards=Object.keys(map).map(function(id){const rows=map[id];if(!rows.length)return'';const first=rows[0];const last=rows[rows.length-1];const prev=rows.length>1?rows[rows.length-2]:null;const fromStart=first.score?Math.round((last.score-first.score)/first.score*1000)/10:0;const fromPrev=prev&&prev.score?Math.round((last.score-prev.score)/prev.score*1000)/10:0;return '<div class="progress-card"><div class="progress-top"><div><div class="progress-name">'+esc(last.name)+'</div><div class="import-meta">od '+esc(first.date)+'</div></div><div class="progress-score">'+esc(formatSet(last.set))+'</div></div><div class="progress-grid"><div class="progress-stat"><div class="progress-label">Od startu</div><div class="progress-value progress-positive">'+(fromStart>=0?'+':'')+fromStart+'%</div></div><div class="progress-stat"><div class="progress-label">Ostatni trening</div><div class="progress-value progress-positive">'+(fromPrev>=0?'+':'')+fromPrev+'%</div></div><div class="progress-stat"><div class="progress-label">Pierwszy wynik</div><div class="progress-value">'+esc(formatSet(first.set))+'</div></div><div class="progress-stat"><div class="progress-label">Wspolczynnik</div><div class="progress-value">'+last.score+'</div></div></div></div>';}).join('');el.innerHTML=cards||'<div class="progress-card"><div class="progress-empty">Brak policzalnych wynikow.</div></div>';}
function renderMeasurements(){const dateInput=document.getElementById('measurement-date');const history=document.getElementById('measurement-history');if(!dateInput||!history)return;ensureTrainingState();if(!dateInput.value)dateInput.value=tdk();const items=(S.bodyMeasurements||[]).slice().sort(function(a,b){return b.date.localeCompare(a.date);});if(items.length===0){history.innerHTML='<div class="measurement-entry"><div class="progress-empty">Pomiary pojawia sie tutaj po pierwszym zapisie.</div></div>';return;}history.innerHTML=items.map(function(item){return '<div class="measurement-entry"><div class="measurement-top"><div><div class="import-type">Pomiar</div><div class="import-title">'+esc(item.date)+'</div></div></div><div class="measurement-entry-grid">'+measurementItem('Waga',item.weight,'kg')+measurementItem('Brzuch',item.waist,'cm')+measurementItem('Biceps',item.biceps,'cm')+measurementItem('Udo',item.thigh,'cm')+measurementItem('Klatka',item.chest,'cm')+'</div></div>';}).join('');}
function measurementItem(label,value,unit){return '<div class="progress-stat"><div class="measurement-label">'+label+'</div><div class="measurement-value">'+(value?esc(value)+' '+unit:'-')+'</div></div>';}
function saveMeasurement(){ensureTrainingState();const item={date:document.getElementById('measurement-date').value||tdk(),weight:document.getElementById('measure-weight').value.trim(),waist:document.getElementById('measure-waist').value.trim(),biceps:document.getElementById('measure-biceps').value.trim(),thigh:document.getElementById('measure-thigh').value.trim(),chest:document.getElementById('measure-chest').value.trim(),createdAt:new Date().toISOString()};S.bodyMeasurements=(S.bodyMeasurements||[]).filter(function(old){return old.date!==item.date;});S.bodyMeasurements.unshift(item);save();renderMeasurements();}
(function(){const baseOpenSection=window.openSection;window.openSection=function(id){baseOpenSection(id);if(id==='trening')renderTrainingDashboard();};const baseRender=window.render;window.render=function(){baseRender();renderTrainingDashboard();};})();
